// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"cron-outbox/internal/configuration"
	"cron-outbox/internal/server"
)

// Injectors from wire.go:

func InitializeArticleService() (*server.App, error) {
	properties := configuration.NewProperties()
	app := server.NewApp(properties)
	return app, nil
}
